/**
 * supabase.ts — Supabase client configuration
 *
 * This file creates a single Supabase client instance that is reused
 * across the entire app. We use environment variables (from .env) so
 * secrets are never hard-coded into source code.
 *
 * HOW IT WORKS:
 *  - import { supabase } from './lib/supabase'
 *  - Then call supabase.from('todos').select() etc.
 */

import { createClient } from '@supabase/supabase-js';

// These values come from your .env file (see .env.example)
// VITE_ prefix is required by Vite to expose env vars to the browser
const supabaseUrl = import.meta.env.VITE_SUPABASE_URL as string;
const supabaseAnonKey = import.meta.env.VITE_SUPABASE_ANON_KEY as string;

// Validate that the environment variables are set
if (!supabaseUrl || !supabaseAnonKey) {
  throw new Error(
    '❌ Missing Supabase environment variables.\n' +
      'Please create a .env file with VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY.\n' +
      'See .env.example for the template.'
  );
}

// createClient sets up the connection to your Supabase project
export const supabase = createClient(supabaseUrl, supabaseAnonKey);

/**
 * TypeScript type that mirrors our "todos" table in Supabase.
 * Every row returned from Supabase will match this shape.
 */
export interface Todo {
  id: string;           // UUID primary key (auto-generated by Supabase)
  text: string;         // The todo task description
  completed: boolean;   // Whether the task is done
  priority: 'low' | 'medium' | 'high'; // Priority level
  created_at: string;   // ISO timestamp (auto-set by Supabase)
  user_id?: string;     // Future: for per-user todos (auth)
}
